# Generated by Django 5.1.5 on 2025-01-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclerentalservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('rent_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='vehiclerentalservice',
        ),
    ]
